### PR TITLE
some refactoring.

### PR DESCRIPTION
**Pull request by seuros**

### CODE REVIEW

**Comment by yelled3** [comment]
@seuros thanks you for starting this. (that's was FAST!)

as I told @mperham in:

> i'm not 100% with the class names and some of the method names... WDYT?

https://github.com/mperham/sidekiq/issues/1699#issuecomment-43689505

do you have any suggestions?

**Comment by seuros** [comment]
I was going to to rename them, but i was sleepy. I don't like the name-spaced method names. 

```
class UserSyncer
  include Sidekiq::ManagerWorker

  sidekiq_delegate_task_to :user_task_worker # or UserTaskWorker
  sidekiq_manager_options :batch_size => 500,
                          :identifier_key => :user_token,
                          :additional_keys => [:status]
end
```

could be 

```
class UserSyncer
  include Sidekiq::ManagerWorker

  delegate_task_to :user_task_worker # or UserTaskWorker
  manager_options :batch_size => 500,
                          :identifier_key => :user_token,
                          :additional_keys => [:status]
end
```

WDYT ?

**Comment by seuros** [comment]
I namespaced the classes, to allow other extensions such as Sidekiq::Sequel::ManagerWorker , Sidekiq::DataMapper::TaskWorker.

**Comment by yelled3** [comment]
@seuros the `sidekiq_` prefix is a convection is from Sidekiq - e.g `sidekiq_options`.
that being said, i'm not sure it's mandatory in this case :-)

**Comment by seuros** [comment]
There is some other tasks to be done.

**Comment by yelled3** [comment]
another thing - if we add support to other ORMs maybe we should rename the repo's name :-)
WDYT?

**Comment by seuros** [comment]
No, it should be another gem: sidekiq-sequel for example

**Comment by seuros** [comment]
```
I don't want to specify the namespace each time - so lets add:

Sidekiq.configure |config|
   config.orm = :active_record # default
end
```

How are you going to handle 2 ORM in the same projects ?

**Comment by yelled3** [comment]
> How are you going to handle 2 ORM in the same projects ?

that's a good point - we can define another option, per worker, which will override the default configured ORM. so you can use only one ORM per worker, which seems reasonable to me. 

> No, it should be another gem: sidekiq-sequel for example
> another gem seems like a good alternative.
> that being said, it will have somewhat duplicated code, since the Manager/Task workers class will have the same logic, aside from the ORM interactions...

lets tryout the config angel first, and if it doesn't play out, we can always split it to another gem.
but let's merge you're cleanup/refactor, and do it in another PR.
cool?

**Comment by seuros** [comment]
> that's a good point - we can define another option, per worker, which will override the default configured ORM. so you can use only one ORM per worker, which seems reasonable to me.  

And we are back at writing more code 

I don't want to pollute Sidekiq namespace with extra modules.

> that being said, it will have somewhat duplicated code, since the Manager/Task workers class will have the same logic, aside from the ORM interactions...

We can always DRY with a third gem, still i don't think we will have duplicated code if we write the code correctly.

**Comment by seuros** [comment]
I think we should avoid using mocks in the tests and use Sidekiq inline feature.

**Comment by yelled3** [comment]
> I think we should avoid using mocks in the tests and use Sidekiq inline feature.

can you please explain why/add example?

**Comment by seuros** [comment]
Because i tried to to add a check  in [here](https://github.com/seuros/sidekiq-activerecord/blob/fcc771f6f3ebea42ed928671b659bde20f3b01bf/lib/sidekiq/active_record/manager_worker.rb#L57)  to be sure that a Worker was passed and not something else. 

Then the tests failed because MockUserWorker is a hash. 
I think can remove half the code and make it very simple if the tests are real.

**Comment by yelled3** [comment]
> to be sure that a Worker was passed

I think this can be done with,

``` ruby
def sidekiq_delegate_task_to(worker_klass)
  case worker_klass
  when String, Symbol
    worker_klass.to_s.split('_').map(&:capitalize).join.constantize
  else
    worker_klass
  end

  raise 'Not a worker class' unless worker_klass.respond_to(:perform)
# OR
  raise 'Not a worker class' if worker_klass.include? Sidekiq::Worker

  get_sidekiq_manager_options[:worker_class] = worker_klass
end

```

**Comment by yelled3** [comment]
> Then the tests failed because MockUserWorker is a hash. 

not sure I understand, but we can replace the `MockUserWorker` with:

``` ruby
class UserTaskWorker
    include Sidekiq::Worker

    def perform(*args)
    end
  end
```

but what does it solve?

**Comment by yelled3** [comment]
@seuros checkout the new WIKI

https://github.com/yelled3/sidekiq-activerecord/wiki

feedback is welcome as always

**Comment by seuros** [comment]
> but what does it solve?

it solve problems in the future, if Sidekiq Api change, we will know immediately where is the problem. 
You should never mock something that you don't control.

**Comment by yelled3** [comment]
> lets tryout the config angel first, and if it doesn't play out, we can always split it to another gem.
> but let's merge you're cleanup/refactor, and do it in another PR.
> cool?

@seuros are we good to merge?
also, would you like to work on the config idea?

**Comment by seuros** [comment]
Merge Ok.
Release not yet. 
We still have to discuss about a good API. If you want to talk by IRC for a brainstorming session , i will be in Freenode in 30 mins from now.

**Comment by yelled3** [comment]
@seuros 
I will try to catch you on IRC.
in the mean while, I opened: https://github.com/yelled3/sidekiq-activerecord/issues/2

**Pull request merged**
