### PR TITLE
Split ORM from Logic

### PR DESCRIPTION
**Pull request by yelled3**
@seuros take a look

I'm starting to thing this split is an overkill - mostly the ManagerWorker part...
maybe we should just have a gem per-ORM, with some duplications

WDYT?

### CODE REVIEW

**Comment by seuros** [comment]
I will take a look at this today and come back to you. Sorry for delay.

**Comment by yelled3** [comment]
@seuros no worries, take your time

**Comment by yelled3** [comment]
> perform_bulk will execute N time UserMailerWorker.perform_async

the reason I use `Sidekiq::Client.push_bulk` is because doing `perform_async` N times is costly, when N is large.

but other then that `perform_bulk` is just an alias of `perform_query_async`, no?

**Comment by yelled3** [comment]
> we can use Activesupport::Concern

I'm trying to minimize dependencies, just like sidekiq is doing:

https://github.com/mperham/sidekiq/blob/ddb58482cfe6b934d632b25c560298c8da4838d8/lib/sidekiq/core_ext.rb#L5

**Comment by seuros** [comment]
> I'm trying to minimize dependencies  

You can't, ActiveRecord already loaded ActiveSupport.

**Comment by seuros** [comment]
> but other then that perform_bulk is just an alias of perform_query_async, no?

yes

> the reason I use Sidekiq::Client.push_bulk is because doing perform_async N times is costly, when N is large.

That why we should do test with live data.

**Comment by yelled3** [comment]
> That why we should do test with live data.

there's no need to benchmark it - already been done. see:

http://stackoverflow.com/a/20692081
http://www.rubydoc.info/github/mperham/sidekiq/Sidekiq/Client.push_bulk

**Comment by yelled3** [comment]
continued in: https://github.com/sidekiq-orm/sidekiq-activerecord/pull/15

**Pull request closed without merging**
